In [6]:
import pyarrow.parquet as pq
import pandas as pd
import numpy as np
import PIL.Image as Image

In [10]:
path = "/Data4/cao/ZiHanCao/exps/HyperspectralTokenizer/data/microG-4M/parquet_format/vqa_and_captioning.parquet"
# pd.read_parquet(path, engine='pyarrow').head()

table = pq.read_table(path).to_pandas()

In [ ]:
table = pq.read_table(path, use_threads=True)
df = table.slice(0, 10).to_pandas()
df

,video_id,caption,qa_pairs
0,PrqcwH8LhDU_003,ESA astronaut Samantha Cristoforetti hovers in...,[{'A': 'ESA astronaut Samantha Cristoforetti.'...
1,PrqcwH8LhDU_004,ESA astronaut Samantha Cristoforetti hovers mi...,[{'A': 'ESA astronaut Samantha Cristoforetti.'...
2,PrqcwH8LhDU_005,ESA astronaut Samantha Cristoforetti hovers be...,[{'A': 'ESA astronaut Samantha Cristoforetti.'...
3,PrqcwH8LhDU_006,ESA astronaut Samantha Cristoforetti floats in...,[{'A': 'ESA astronaut Samantha Cristoforetti.'...
4,PrqcwH8LhDU_007,"Glancing upward, the astronaut Samantha Cristo...","[{'A': 'Samantha Cristoforetti.', 'Q': 'Who is..."
5,PrqcwH8LhDU_008,ESA astronaut Samantha Cristoforetti presents ...,[{'A': 'ESA astronaut Samantha Cristoforetti.'...
6,PrqcwH8LhDU_009,ESA astronaut Samantha Cristoforetti holding t...,[{'A': 'ESA astronaut Samantha Cristoforetti.'...
7,PrqcwH8LhDU_010,"With a gentle push, the astronaut Samantha Cri...","[{'A': 'Samantha Cristoforetti.', 'Q': 'Who is..."
8,PrqcwH8LhDU_011,The astronaut Samantha Cristoforetti in a turq...,[{'A': 'The astronaut is Samantha Cristoforett...
9,PrqcwH8LhDU_012,The astronaut Samantha Cristoforetti holds the...,[{'A': 'The astronaut Samantha Cristoforetti i...

In [27]:
import dask.dataframe as dd

df = dd.read_parquet(
    path,
)
df = df.loc[20:30].compute()

In [30]:
df

,video_id,caption,qa_pairs
20,PrqcwH8LhDU_023,The astronaut Samantha Cristoforetti holds the...,[{'A': 'The astronaut Samantha Cristoforetti i...
21,PrqcwH8LhDU_024,A clear plastic bag appears in Samantha Cristo...,"[{'A': 'A clear plastic bag.', 'Q': 'What is S..."
22,PrqcwH8LhDU_025,The astronaut Samantha Cristoforetti tucks the...,"[{'A': 'Samantha Cristoforetti.', 'Q': 'Who is..."
23,PrqcwH8LhDU_026,"Turning toward the wall, the astronaut Samanth...","[{'A': 'Samantha Cristoforetti.', 'Q': 'Who is..."
24,PrqcwH8LhDU_027,The astronaut Samantha Cristoforetti removes a...,"[{'A': 'Samantha Cristoforetti.', 'Q': 'Who is..."
25,PrqcwH8LhDU_028,"A small silver-foil packet is detached, inspec...",[{'A': 'The astronaut is inspecting it by flip...
26,PrqcwH8LhDU_029,The astronaut grasps a thin off-white rectangu...,"[{'A': 'A thin off-white rectangular pad.', 'Q..."
27,PrqcwH8LhDU_030,"The astronaut lifts a shiny metallic pouch, fl...",[{'A': 'The astronaut lifts the shiny metallic...
28,PrqcwH8LhDU_031,"The astronaut floats upright inside the frame,...","[{'A': 'The astronaut.', 'Q': 'Who is holding ..."
29,PrqcwH8LhDU_033,The astronaut faces the lens with arms spread ...,[{'A': 'She is facing the lens with arms sprea...
30,PrqcwH8LhDU_034,"Turned fully sideways, the astronaut selects a...",[{'A': 'The astronaut is selecting a single wh...